"""create chat core tables

Revision ID: 397ab6d52467
Revises: 
Create Date: 2026-06-30 10:28:06.026994+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '397ab6d52467'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_decision_log',
    sa.Column('session_id', sa.String(length=36), nullable=False, comment='会话 ID'),
    sa.Column('message_id', sa.String(length=36), nullable=True, comment='用户消息 ID'),
    sa.Column('original_text', sa.Text(), nullable=False, comment='原始文本'),
    sa.Column('normalized_text', sa.Text(), nullable=True, comment='归一化文本'),
    sa.Column('intent_result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='意图识别结果'),
    sa.Column('slot_result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='槽位抽取结果'),
    sa.Column('selected_skill', sa.String(length=64), nullable=True, comment='命中的 Skill'),
    sa.Column('status', sa.String(length=32), nullable=True, comment='最终状态'),
    sa.Column('decision_source', sa.String(length=32), nullable=True, comment='决策来源'),
    sa.Column('graph_trace_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='图执行轨迹'),
    sa.Column('latency_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='各阶段耗时'),
    sa.Column('error_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='错误信息'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键，UUID 字符串'),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_decision_log_created_at', 'chat_decision_log', ['created_at'], unique=False)
    op.create_index('ix_chat_decision_log_tenant_session_created', 'chat_decision_log', ['tenant_id', 'session_id', 'created_at'], unique=False)
    op.create_index('ix_chat_decision_log_tenant_skill', 'chat_decision_log', ['tenant_id', 'selected_skill'], unique=False)
    op.create_index('ix_chat_decision_log_tenant_status', 'chat_decision_log', ['tenant_id', 'status'], unique=False)
    op.create_table('chat_dialog_state',
    sa.Column('session_id', sa.String(length=36), nullable=False, comment='会话 ID'),
    sa.Column('state', sa.String(length=16), server_default='IDLE', nullable=False, comment='状态机状态'),
    sa.Column('active_task_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='当前任务'),
    sa.Column('task_stack_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='挂起任务栈'),
    sa.Column('context_stacks_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='上下文对象栈'),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False, comment='乐观锁版本号'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键，UUID 字符串'),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户 ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'session_id', name='uq_chat_dialog_state_tenant_session')
    )
    op.create_table('chat_message',
    sa.Column('session_id', sa.String(length=36), nullable=False, comment='会话 ID'),
    sa.Column('role', sa.String(length=16), nullable=False, comment='角色'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('intent', sa.String(length=64), nullable=True, comment='最终意图'),
    sa.Column('status', sa.String(length=32), nullable=True, comment='本轮处理状态'),
    sa.Column('slots_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='槽位'),
    sa.Column('trace_id', sa.String(length=64), nullable=True, comment='链路追踪 ID'),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='扩展字段'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键，UUID 字符串'),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_message_tenant_intent', 'chat_message', ['tenant_id', 'intent'], unique=False)
    op.create_index('ix_chat_message_tenant_session_created', 'chat_message', ['tenant_id', 'session_id', 'created_at'], unique=False)
    op.create_index('ix_chat_message_trace_id', 'chat_message', ['trace_id'], unique=False)
    op.create_table('chat_session',
    sa.Column('user_id', sa.String(length=64), nullable=False, comment='用户 ID'),
    sa.Column('channel', sa.String(length=32), nullable=False, comment='渠道'),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False, comment='会话状态：active/closed/handoff'),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='扩展字段'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键，UUID 字符串'),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户 ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_session_created_at', 'chat_session', ['created_at'], unique=False)
    op.create_index('ix_chat_session_tenant_status', 'chat_session', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_chat_session_tenant_user', 'chat_session', ['tenant_id', 'user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_session_tenant_user', table_name='chat_session')
    op.drop_index('ix_chat_session_tenant_status', table_name='chat_session')
    op.drop_index('ix_chat_session_created_at', table_name='chat_session')
    op.drop_table('chat_session')
    op.drop_index('ix_chat_message_trace_id', table_name='chat_message')
    op.drop_index('ix_chat_message_tenant_session_created', table_name='chat_message')
    op.drop_index('ix_chat_message_tenant_intent', table_name='chat_message')
    op.drop_table('chat_message')
    op.drop_table('chat_dialog_state')
    op.drop_index('ix_chat_decision_log_tenant_status', table_name='chat_decision_log')
    op.drop_index('ix_chat_decision_log_tenant_skill', table_name='chat_decision_log')
    op.drop_index('ix_chat_decision_log_tenant_session_created', table_name='chat_decision_log')
    op.drop_index('ix_chat_decision_log_created_at', table_name='chat_decision_log')
    op.drop_table('chat_decision_log')
    # ### end Alembic commands ###
