"""add trgm gin indexes for keyword search

Revision ID: 4f5b61d63ede
Revises: 09543f8836cd
Create Date: 2026-07-02 10:04:11.031777+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f5b61d63ede'
down_revision: Union[str, None] = '09543f8836cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # pg_trgm：三元组模糊匹配扩展（PG13+ 为 trusted，库 owner 即可创建）。
    # kb_chunk.content 与 product_item.name 的 ILIKE '%kw%' 检索依赖它
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_kb_chunk_content_trgm', 'kb_chunk', ['content'], unique=False, postgresql_using='gin', postgresql_ops={'content': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_product_item_tenant_name'), table_name='product_item')
    op.create_index('ix_product_item_name_trgm', 'product_item', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_item_name_trgm', table_name='product_item', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index(op.f('ix_product_item_tenant_name'), 'product_item', ['tenant_id', 'name'], unique=False)
    op.drop_index('ix_kb_chunk_content_trgm', table_name='kb_chunk', postgresql_using='gin', postgresql_ops={'content': 'gin_trgm_ops'})
    # ### end Alembic commands ###
