"""kb_chunk section_path for parent-child

Revision ID: f7424f8caa4d
Revises: df385246e05d
Create Date: 2026-07-03 02:50:46.633191+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7424f8caa4d'
down_revision: Union[str, None] = 'df385246e05d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kb_chunk', sa.Column('section_path', sa.String(length=512), nullable=True, comment='章节路径'))
    op.create_index('ix_kb_chunk_doc_section', 'kb_chunk', ['document_id', 'section_path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_kb_chunk_doc_section', table_name='kb_chunk')
    op.drop_column('kb_chunk', 'section_path')
    # ### end Alembic commands ###
