"""add user_memory

Revision ID: d7395298fab5
Revises: 540fed33963e
Create Date: 2026-07-03 02:16:13.389657+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7395298fab5'
down_revision: Union[str, None] = '540fed33963e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_memory',
    sa.Column('user_id', sa.String(length=64), nullable=False, comment='用户 ID'),
    sa.Column('kind', sa.String(length=16), server_default='fact', nullable=False, comment='类别'),
    sa.Column('content', sa.Text(), nullable=False, comment='记忆内容'),
    sa.Column('source_session_id', sa.String(length=36), nullable=True, comment='来源会话'),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False, comment='状态'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键，UUID 字符串'),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户 ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_memory_tenant_user', 'user_memory', ['tenant_id', 'user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_memory_tenant_user', table_name='user_memory')
    op.drop_table('user_memory')
    # ### end Alembic commands ###
