"""add chat_handoff_ticket

Revision ID: 7cfc385fd19a
Revises: f7424f8caa4d
Create Date: 2026-07-03 03:29:37.952329+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7cfc385fd19a'
down_revision: Union[str, None] = 'f7424f8caa4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_handoff_ticket',
    sa.Column('session_id', sa.String(length=36), nullable=False, comment='会话 ID'),
    sa.Column('user_id', sa.String(length=64), nullable=False, comment='用户 ID'),
    sa.Column('reason', sa.String(length=32), nullable=False, comment='触发原因'),
    sa.Column('source_intent', sa.String(length=64), nullable=True, comment='触发时的意图码'),
    sa.Column('status', sa.String(length=16), server_default='PENDING', nullable=False, comment='工单状态'),
    sa.Column('assignee', sa.String(length=64), nullable=True, comment='坐席标识'),
    sa.Column('context_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='上下文移交包'),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True, comment='解决时间'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键，UUID 字符串'),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户 ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_handoff_tenant_session', 'chat_handoff_ticket', ['tenant_id', 'session_id'], unique=False)
    op.create_index('ix_chat_handoff_tenant_status', 'chat_handoff_ticket', ['tenant_id', 'status'], unique=False)
    op.create_index('uq_chat_handoff_open_session', 'chat_handoff_ticket', ['tenant_id', 'session_id'], unique=True, postgresql_where=sa.text("status IN ('PENDING', 'ASSIGNED')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_chat_handoff_open_session', table_name='chat_handoff_ticket', postgresql_where=sa.text("status IN ('PENDING', 'ASSIGNED')"))
    op.drop_index('ix_chat_handoff_tenant_status', table_name='chat_handoff_ticket')
    op.drop_index('ix_chat_handoff_tenant_session', table_name='chat_handoff_ticket')
    op.drop_table('chat_handoff_ticket')
    # ### end Alembic commands ###
