"""add api_credential

Revision ID: 540fed33963e
Revises: 4f5b61d63ede
Create Date: 2026-07-02 10:36:52.486201+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '540fed33963e'
down_revision: Union[str, None] = '4f5b61d63ede'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_credential',
    sa.Column('key_id', sa.String(length=64), nullable=False, comment='公开键标识'),
    sa.Column('secret_hash', sa.String(length=128), nullable=False, comment='密钥哈希'),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='权限范围'),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False, comment='状态'),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True, comment='最近使用时间'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键，UUID 字符串'),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户 ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_id')
    )
    op.create_index('ix_api_credential_tenant_status', 'api_credential', ['tenant_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_api_credential_tenant_status', table_name='api_credential')
    op.drop_table('api_credential')
    # ### end Alembic commands ###
