"""add chat_feedback and quality_daily view

Revision ID: 1316d5cadc06
Revises: 7cfc385fd19a
Create Date: 2026-07-03 04:16:44.186761+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1316d5cadc06'
down_revision: Union[str, None] = '7cfc385fd19a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_feedback',
    sa.Column('session_id', sa.String(length=36), nullable=False, comment='会话 ID'),
    sa.Column('message_id', sa.String(length=36), nullable=False, comment='消息 ID'),
    sa.Column('rating', sa.String(length=8), nullable=False, comment='评价 up/down'),
    sa.Column('comment', sa.Text(), nullable=True, comment='补充说明'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键，UUID 字符串'),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_feedback_tenant_rating', 'chat_feedback', ['tenant_id', 'rating', 'created_at'], unique=False)
    op.create_index('uq_chat_feedback_message', 'chat_feedback', ['tenant_id', 'message_id'], unique=True)

    # 质量看板物化视图：按 租户×天 聚合决策日志（Stage 09）。
    # 高频看板查询不扫原表；刷新走 scripts/refresh_quality_views.py
    # （CONCURRENTLY 依赖下面的唯一索引，刷新不锁读）。
    op.execute(
        """
        CREATE MATERIALIZED VIEW quality_daily AS
        SELECT
            tenant_id,
            (created_at AT TIME ZONE 'UTC')::date            AS day,
            count(*)                                         AS turns,
            count(DISTINCT session_id)                       AS sessions,
            count(*) FILTER (WHERE status = 'DONE')          AS done_turns,
            count(*) FILTER (WHERE status = 'FALLBACK')      AS fallback_turns,
            count(*) FILTER (WHERE status = 'HANDOFF')       AS handoff_turns,
            count(*) FILTER (WHERE status = 'FAILED')        AS failed_turns,
            count(*) FILTER (
                WHERE (intent_result_json ->> 'confidence')::float < 0.6
            )                                                AS low_conf_turns,
            count(*) FILTER (
                WHERE (retrieval_json ->> 'refused')::boolean IS TRUE
            )                                                AS rag_refused_turns,
            percentile_cont(0.5) WITHIN GROUP (
                ORDER BY (latency_json ->> 'total_ms')::float
            )                                                AS p50_latency_ms,
            percentile_cont(0.95) WITHIN GROUP (
                ORDER BY (latency_json ->> 'total_ms')::float
            )                                                AS p95_latency_ms
        FROM chat_decision_log
        GROUP BY tenant_id, day
        """
    )
    op.execute("CREATE UNIQUE INDEX uq_quality_daily ON quality_daily (tenant_id, day)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP MATERIALIZED VIEW IF EXISTS quality_daily")
    op.drop_index('uq_chat_feedback_message', table_name='chat_feedback')
    op.drop_index('ix_chat_feedback_tenant_rating', table_name='chat_feedback')
    op.drop_table('chat_feedback')
    # ### end Alembic commands ###
