"""add product_item and kb_document parser columns

Revision ID: c636c149ca15
Revises: ccef3980bc0e
Create Date: 2026-07-02 07:52:39.159505+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c636c149ca15'
down_revision: Union[str, None] = 'ccef3980bc0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_item',
    sa.Column('product_code', sa.String(length=64), nullable=True, comment='商品编码'),
    sa.Column('name', sa.String(length=256), nullable=False, comment='商品名称'),
    sa.Column('category', sa.String(length=64), nullable=True, comment='分类'),
    sa.Column('price_cents', sa.Integer(), nullable=True, comment='价格（分）'),
    sa.Column('stock', sa.Integer(), nullable=True, comment='库存'),
    sa.Column('attrs_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='规格属性'),
    sa.Column('description', sa.Text(), nullable=True, comment='商品简介'),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False, comment='状态'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键，UUID 字符串'),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户 ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_product_item_tenant_code', 'product_item', ['tenant_id', 'product_code'], unique=False)
    op.create_index('ix_product_item_tenant_name', 'product_item', ['tenant_id', 'name'], unique=False)
    op.create_index('ix_product_item_tenant_status', 'product_item', ['tenant_id', 'status'], unique=False)
    op.add_column('kb_document', sa.Column('file_name', sa.String(length=256), nullable=True, comment='原始文件名'))
    op.add_column('kb_document', sa.Column('parser', sa.String(length=32), nullable=True, comment='解析器'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kb_document', 'parser')
    op.drop_column('kb_document', 'file_name')
    op.drop_index('ix_product_item_tenant_status', table_name='product_item')
    op.drop_index('ix_product_item_tenant_name', table_name='product_item')
    op.drop_index('ix_product_item_tenant_code', table_name='product_item')
    op.drop_table('product_item')
    # ### end Alembic commands ###
