"""stage16 kb document versioning and scheduling

Revision ID: 3a1e7630141b
Revises: b546c33dea6f
Create Date: 2026-07-04 04:09:11.082264+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a1e7630141b'
down_revision: Union[str, None] = 'b546c33dea6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kb_document_version',
    sa.Column('document_id', sa.String(length=36), nullable=False, comment='所属文档 ID'),
    sa.Column('version', sa.Integer(), nullable=False, comment='版本号'),
    sa.Column('title', sa.String(length=256), nullable=False, comment='标题'),
    sa.Column('raw_content', sa.Text(), nullable=False, comment='原始内容'),
    sa.Column('source_type', sa.String(length=32), nullable=False, comment='来源类型'),
    sa.Column('editor', sa.String(length=64), nullable=True, comment='编辑者'),
    sa.Column('note', sa.Text(), nullable=True, comment='编辑说明'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键，UUID 字符串'),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kb_doc_version_tenant_doc', 'kb_document_version', ['tenant_id', 'document_id', 'version'], unique=False)
    op.add_column('kb_document', sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True, comment='定时生效时间'))
    op.add_column('kb_document', sa.Column('expire_at', sa.DateTime(timezone=True), nullable=True, comment='定时失效时间'))
    op.add_column('kb_document', sa.Column('published_version', sa.Integer(), nullable=True, comment='当前线上版本号'))
    # 数据迁移（Stage 16 零回归）：现有 active 文档 → published（可检索态语义不变），
    # 并回填一个线上版本号（1）与版本历史行，让存量文档进入版本体系
    op.execute("UPDATE kb_document SET status = 'published', published_version = 1 WHERE status = 'active'")
    op.execute(
        "INSERT INTO kb_document_version "
        "(id, tenant_id, document_id, version, title, raw_content, source_type, editor, created_at) "
        "SELECT gen_random_uuid()::text, tenant_id, id, 1, title, raw_content, source_type, "
        "'migration', now() FROM kb_document WHERE published_version = 1"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE kb_document SET status = 'active' WHERE status = 'published'")
    op.drop_column('kb_document', 'published_version')
    op.drop_column('kb_document', 'expire_at')
    op.drop_column('kb_document', 'effective_from')
    op.drop_index('ix_kb_doc_version_tenant_doc', table_name='kb_document_version')
    op.drop_table('kb_document_version')
    # ### end Alembic commands ###
