"""add kb tables and decision_log retrieval_json

Revision ID: ccef3980bc0e
Revises: 397ab6d52467
Create Date: 2026-07-02 05:06:05.417494+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ccef3980bc0e'
down_revision: Union[str, None] = '397ab6d52467'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faq_entry',
    sa.Column('question', sa.String(length=512), nullable=False, comment='标准问题'),
    sa.Column('answer', sa.Text(), nullable=False, comment='标准答案'),
    sa.Column('question_embedding_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='问题 embedding'),
    sa.Column('category', sa.String(length=64), nullable=True, comment='分类'),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False, comment='状态'),
    sa.Column('hit_count', sa.Integer(), server_default='0', nullable=False, comment='命中次数'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键，UUID 字符串'),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户 ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_faq_entry_tenant_category', 'faq_entry', ['tenant_id', 'category'], unique=False)
    op.create_index('ix_faq_entry_tenant_status', 'faq_entry', ['tenant_id', 'status'], unique=False)
    op.create_table('kb_chunk',
    sa.Column('document_id', sa.String(length=36), nullable=False, comment='所属文档 ID'),
    sa.Column('chunk_index', sa.Integer(), nullable=False, comment='分块序号'),
    sa.Column('content', sa.Text(), nullable=False, comment='分块内容'),
    sa.Column('embedding_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='embedding 向量'),
    sa.Column('token_count', sa.Integer(), nullable=True, comment='token 数'),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='过滤维度（category/product_id 等）'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键，UUID 字符串'),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kb_chunk_tenant_document', 'kb_chunk', ['tenant_id', 'document_id'], unique=False)
    op.create_table('kb_document',
    sa.Column('source_type', sa.String(length=32), nullable=False, comment='来源类型'),
    sa.Column('title', sa.String(length=256), nullable=False, comment='文档标题'),
    sa.Column('raw_content', sa.Text(), nullable=False, comment='原始内容'),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False, comment='状态'),
    sa.Column('needs_reindex', sa.Boolean(), server_default='false', nullable=False, comment='待重建索引'),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='扩展字段（分类/商品ID等过滤维度）'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键，UUID 字符串'),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户 ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kb_document_tenant_source', 'kb_document', ['tenant_id', 'source_type'], unique=False)
    op.create_index('ix_kb_document_tenant_status', 'kb_document', ['tenant_id', 'status'], unique=False)
    op.add_column('chat_decision_log', sa.Column('retrieval_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='检索过程'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_decision_log', 'retrieval_json')
    op.drop_index('ix_kb_document_tenant_status', table_name='kb_document')
    op.drop_index('ix_kb_document_tenant_source', table_name='kb_document')
    op.drop_table('kb_document')
    op.drop_index('ix_kb_chunk_tenant_document', table_name='kb_chunk')
    op.drop_table('kb_chunk')
    op.drop_index('ix_faq_entry_tenant_status', table_name='faq_entry')
    op.drop_index('ix_faq_entry_tenant_category', table_name='faq_entry')
    op.drop_table('faq_entry')
    # ### end Alembic commands ###
