"""stage15 chat_csat and quality_daily csat

Revision ID: b546c33dea6f
Revises: 504825e337b1
Create Date: 2026-07-04 01:02:12.076937+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b546c33dea6f'
down_revision: Union[str, None] = '504825e337b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_csat',
    sa.Column('session_id', sa.String(length=36), nullable=False, comment='会话 ID'),
    sa.Column('user_id', sa.String(length=64), nullable=False, comment='用户 ID'),
    sa.Column('score', sa.Integer(), nullable=False, comment='评分 1-5'),
    sa.Column('comment', sa.Text(), nullable=True, comment='附言'),
    sa.Column('trigger', sa.String(length=32), nullable=False, comment='触发场景'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键，UUID 字符串'),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_csat_tenant_created', 'chat_csat', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_chat_csat_tenant_session', 'chat_csat', ['tenant_id', 'session_id'], unique=False)

    # 重建 quality_daily：加 CSAT 均分与样本量列（Stage 15）
    op.execute("DROP MATERIALIZED VIEW IF EXISTS quality_daily")
    op.execute(
        """
        CREATE MATERIALIZED VIEW quality_daily AS
        WITH decision AS (
            SELECT
                tenant_id,
                (created_at AT TIME ZONE 'UTC')::date            AS day,
                count(*)                                         AS turns,
                count(DISTINCT session_id)                       AS sessions,
                count(*) FILTER (WHERE status = 'DONE')          AS done_turns,
                count(*) FILTER (WHERE status = 'FALLBACK')      AS fallback_turns,
                count(*) FILTER (WHERE status = 'HANDOFF')       AS handoff_turns,
                count(*) FILTER (WHERE status = 'FAILED')        AS failed_turns,
                count(*) FILTER (
                    WHERE (intent_result_json ->> 'confidence')::float < 0.6
                )                                                AS low_conf_turns,
                count(*) FILTER (
                    WHERE (retrieval_json ->> 'refused')::boolean IS TRUE
                )                                                AS rag_refused_turns,
                percentile_cont(0.5) WITHIN GROUP (
                    ORDER BY (latency_json ->> 'total_ms')::float
                )                                                AS p50_latency_ms,
                percentile_cont(0.95) WITHIN GROUP (
                    ORDER BY (latency_json ->> 'total_ms')::float
                )                                                AS p95_latency_ms
            FROM chat_decision_log
            GROUP BY tenant_id, day
        ), csat AS (
            SELECT tenant_id,
                   (created_at AT TIME ZONE 'UTC')::date AS day,
                   round(avg(score)::numeric, 2)          AS csat_avg,
                   count(*)                               AS csat_count
            FROM chat_csat
            GROUP BY tenant_id, day
        )
        SELECT decision.*, csat.csat_avg, csat.csat_count
        FROM decision LEFT JOIN csat USING (tenant_id, day)
        """
    )
    op.execute("CREATE UNIQUE INDEX uq_quality_daily ON quality_daily (tenant_id, day)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 还原不带 CSAT 列的 quality_daily（与 1316d5cadc06 定义一致）
    op.execute("DROP MATERIALIZED VIEW IF EXISTS quality_daily")
    op.execute(
        """
        CREATE MATERIALIZED VIEW quality_daily AS
        SELECT
            tenant_id,
            (created_at AT TIME ZONE 'UTC')::date            AS day,
            count(*)                                         AS turns,
            count(DISTINCT session_id)                       AS sessions,
            count(*) FILTER (WHERE status = 'DONE')          AS done_turns,
            count(*) FILTER (WHERE status = 'FALLBACK')      AS fallback_turns,
            count(*) FILTER (WHERE status = 'HANDOFF')       AS handoff_turns,
            count(*) FILTER (WHERE status = 'FAILED')        AS failed_turns,
            count(*) FILTER (
                WHERE (intent_result_json ->> 'confidence')::float < 0.6
            )                                                AS low_conf_turns,
            count(*) FILTER (
                WHERE (retrieval_json ->> 'refused')::boolean IS TRUE
            )                                                AS rag_refused_turns,
            percentile_cont(0.5) WITHIN GROUP (
                ORDER BY (latency_json ->> 'total_ms')::float
            )                                                AS p50_latency_ms,
            percentile_cont(0.95) WITHIN GROUP (
                ORDER BY (latency_json ->> 'total_ms')::float
            )                                                AS p95_latency_ms
        FROM chat_decision_log
        GROUP BY tenant_id, day
        """
    )
    op.execute("CREATE UNIQUE INDEX uq_quality_daily ON quality_daily (tenant_id, day)")
    op.drop_index('ix_chat_csat_tenant_session', table_name='chat_csat')
    op.drop_index('ix_chat_csat_tenant_created', table_name='chat_csat')
    op.drop_table('chat_csat')
    # ### end Alembic commands ###
