"""stage13 credential expires_at and faq needs_reindex

Revision ID: 504825e337b1
Revises: 1316d5cadc06
Create Date: 2026-07-03 07:25:31.575972+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '504825e337b1'
down_revision: Union[str, None] = '1316d5cadc06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_credential', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='过期时间'))
    op.add_column('faq_entry', sa.Column('needs_reindex', sa.Boolean(), server_default='false', nullable=False, comment='待重建索引'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faq_entry', 'needs_reindex')
    op.drop_column('api_credential', 'expires_at')
    # ### end Alembic commands ###
