"""add customer_journey (Stage 38)

Revision ID: 5c31f6db723b
Revises: ae19ae99e128
Create Date: 2026-08-06 01:46:17.139456+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c31f6db723b'
down_revision: Union[str, None] = 'ae19ae99e128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_journey',
    sa.Column('user_id', sa.String(length=64), nullable=False, comment='客户标识'),
    sa.Column('stage', sa.String(length=20), server_default='NEW', nullable=False, comment='旅程阶段'),
    sa.Column('at_risk', sa.Boolean(), server_default='false', nullable=False, comment='流失风险叠加标记（非阶段）'),
    sa.Column('signals_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='转移证据史'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键，UUID 字符串'),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户 ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customer_journey_stage', 'customer_journey', ['tenant_id', 'stage'], unique=False)
    op.create_index('uq_customer_journey_tenant_user', 'customer_journey', ['tenant_id', 'user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_customer_journey_tenant_user', table_name='customer_journey')
    op.drop_index('ix_customer_journey_stage', table_name='customer_journey')
    op.drop_table('customer_journey')
    # ### end Alembic commands ###
