"""add chat_task and chat_tool_call

Revision ID: 09543f8836cd
Revises: c636c149ca15
Create Date: 2026-07-02 09:28:15.612418+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09543f8836cd'
down_revision: Union[str, None] = 'c636c149ca15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_task',
    sa.Column('session_id', sa.String(length=36), nullable=False, comment='会话 ID'),
    sa.Column('intent', sa.String(length=64), nullable=False, comment='任务意图'),
    sa.Column('skill_id', sa.String(length=64), nullable=False, comment='Skill 标识'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='任务状态'),
    sa.Column('collected_slots_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='已收集槽位'),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True, comment='用户确认时间'),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True, comment='执行时间'),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='执行结果（工单号等）'),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False, comment='乐观锁版本号'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键，UUID 字符串'),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户 ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_task_tenant_session', 'chat_task', ['tenant_id', 'session_id'], unique=False)
    op.create_index('ix_chat_task_tenant_status', 'chat_task', ['tenant_id', 'status'], unique=False)
    op.create_table('chat_tool_call',
    sa.Column('session_id', sa.String(length=36), nullable=False, comment='会话 ID'),
    sa.Column('task_id', sa.String(length=36), nullable=True, comment='任务 ID'),
    sa.Column('tool_id', sa.String(length=64), nullable=False, comment='工具标识'),
    sa.Column('request_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='入参（脱敏）'),
    sa.Column('response_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='返回数据'),
    sa.Column('ok', sa.Boolean(), nullable=False, comment='是否成功'),
    sa.Column('error_code', sa.String(length=32), nullable=True, comment='错误码'),
    sa.Column('latency_ms', sa.Float(), nullable=True, comment='耗时（毫秒）'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键，UUID 字符串'),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_tool_call_tenant_session', 'chat_tool_call', ['tenant_id', 'session_id'], unique=False)
    op.create_index('ix_chat_tool_call_tenant_tool', 'chat_tool_call', ['tenant_id', 'tool_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_tool_call_tenant_tool', table_name='chat_tool_call')
    op.drop_index('ix_chat_tool_call_tenant_session', table_name='chat_tool_call')
    op.drop_table('chat_tool_call')
    op.drop_index('ix_chat_task_tenant_status', table_name='chat_task')
    op.drop_index('ix_chat_task_tenant_session', table_name='chat_task')
    op.drop_table('chat_task')
    # ### end Alembic commands ###
