"""add chat_service_case (Stage 34)

Revision ID: ae19ae99e128
Revises: a7c2f1e9d3b4
Create Date: 2026-08-05 10:07:06.250460+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae19ae99e128'
down_revision: Union[str, None] = 'a7c2f1e9d3b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_service_case',
    sa.Column('case_no', sa.String(length=32), nullable=False, comment='人读编号 CS...'),
    sa.Column('user_id', sa.String(length=64), nullable=False, comment='客户标识'),
    sa.Column('case_type', sa.String(length=32), nullable=False, comment='Case 类型'),
    sa.Column('status', sa.String(length=20), server_default='OPEN', nullable=False, comment='状态'),
    sa.Column('priority', sa.String(length=8), server_default='NORMAL', nullable=False, comment='LOW/NORMAL/HIGH'),
    sa.Column('owner_type', sa.String(length=8), server_default='AI', nullable=False, comment='AI/HUMAN'),
    sa.Column('owner_id', sa.String(length=64), nullable=True, comment='认领者'),
    sa.Column('sla_due_at', sa.DateTime(timezone=True), nullable=True, comment='SLA 解决时限'),
    sa.Column('related_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='关联对象'),
    sa.Column('resolution_code', sa.String(length=64), nullable=True, comment='解决口径码'),
    sa.Column('reopen_count', sa.Integer(), server_default='0', nullable=False, comment='重开次数'),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True, comment='解决时间'),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True, comment='关闭时间'),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='扩展元数据'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键，UUID 字符串'),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户 ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_service_case_sla', 'chat_service_case', ['sla_due_at'], unique=False)
    op.create_index('ix_chat_service_case_tenant_status', 'chat_service_case', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_chat_service_case_tenant_user', 'chat_service_case', ['tenant_id', 'user_id'], unique=False)
    op.create_index('uq_chat_service_case_active', 'chat_service_case', ['tenant_id', 'user_id', 'case_type'], unique=True, postgresql_where=sa.text("status IN ('OPEN','IN_PROGRESS','WAITING_CUSTOMER','WAITING_INTERNAL','WAITING_EXTERNAL','REOPENED','ESCALATED')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_chat_service_case_active', table_name='chat_service_case', postgresql_where=sa.text("status IN ('OPEN','IN_PROGRESS','WAITING_CUSTOMER','WAITING_INTERNAL','WAITING_EXTERNAL','REOPENED','ESCALATED')"))
    op.drop_index('ix_chat_service_case_tenant_user', table_name='chat_service_case')
    op.drop_index('ix_chat_service_case_tenant_status', table_name='chat_service_case')
    op.drop_index('ix_chat_service_case_sla', table_name='chat_service_case')
    op.drop_table('chat_service_case')
    # ### end Alembic commands ###
